application: hotel
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /templates
  static_dir: static 

- url: /.*
  script: urls.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest